package com.techhub.util.core
import org.json.JSONObject
class CountryCurrencyHelper {
    private fun jsonToHashMap(): HashMap<String, String> {
        if(currencyMap.isNullOrEmpty()) {
            val jsonObject = JSONObject(getCountryJson())
            val keys: Iterator<String> = jsonObject.keys()
            val hashMap = HashMap<String, String>()

            while (keys.hasNext()) {
                val key = keys.next()
                val value = jsonObject.getString(key)
                hashMap[key] = value
            }
            return hashMap
        }else{
            return currencyMap
        }
    }

    fun getCountryJson(): String {
       return """
        {
            "AAD": "$",
            "AED": "إ.د",
            "AFN": "؋",
            "ALL": "Lek",
            "AMD": "֏",
            "ANG": "ƒ",
            "AOA": "Kz",
            "ARS": "$",
            "AUD": "$",
            "AWG": "ƒ",
            "AZN": "m",
            "BAM": "KM",
            "BBD": "Bds$",
            "BDT": "৳",
            "BGN": "Лв.",
            "BHD": ".د.ب",
            "BIF": "FBu",
            "BMD": "$",
            "BND": "B$",
            "BOB": "Bs.",
            "BRL": "R$",
            "BSD": "B$",
            "BTN": "Nu.",
            "BWP": "P",
            "BYN": "Br",
            "BZD": "$",
            "CAD": "$",
            "CDF": "FC",
            "CHF": "CHf",
            "CLP": "$",
            "CNY": "¥",
            "COP": "$",
            "CRC": "₡",
            "CUP": "$",
            "CVE": "$",
            "CZK": "Kč",
            "DJF": "Fdj",
            "DKK": "Kr.",
            "DOP": "$",
            "DZD": "دج",
            "EGP": "ج.م",
            "ERN": "Nfk",
            "ETB": "Nkf",
            "EUR": "€",
            "FJD": "FJ$",
            "FKP": "£",
            "GBP": "£",
            "GEL": "ლ",
            "GHS": "GH₵",
            "GIP": "£",
            "GMD": "D",
            "GNF": "FG",
            "GTQ": "Q",
            "GYD": "$",
            "HKD": "$",
            "HNL": "L",
            "HRK": "kn",
            "HTG": "G",
            "HUF": "Ft",
            "IDR": "Rp",
            "ILS": "₪",
            "INR": "₹",
            "IQD": "د.ع",
            "IRR": "﷼",
            "ISK": "kr",
            "JMD": "J$",
            "JOD": "ا.د",
            "JPY": "¥",
            "KES": "KSh",
            "KGS": "лв",
            "KHR": "KHR",
            "KMF": "CF",
            "KPW": "₩",
            "KRW": "₩",
            "KWD": "ك.د",
            "KYD": "$",
            "KZT": "лв",
            "LAK": "₭",
            "LBP": "£",
            "LKR": "Rs",
            "LRD": "$",
            "LSL": "L",
            "LYD": "د.ل",
            "MAD": "MAD",
            "MDL": "L",
            "MGA": "Ar",
            "MKD": "ден",
            "MMK": "K",
            "MNT": "₮",
            "MOP": "$",
            "MRO": "MRU",
            "MUR": "₨",
            "MVR": "Rf",
            "MWK": "MK",
            "MXN": "$",
            "MYR": "RM",
            "MZN": "MT",
            "NAD": "$",
            "NGN": "₦",
            "NIO": "C$",
            "NOK": "kr",
            "NPR": "₨",
            "NZD": "$",
            "OMR": ".ع.ر",
            "PAB": "B/.",
            "PEN": "S/.",
            "PGK": "K",
            "PHP": "₱",
            "PKR": "₨",
            "PLN": "zł",
            "PYG": "₲",
            "QAR": "ق.ر",
            "RON": "lei",
            "RSD": "din",
            "RUB": "₽",
            "RWF": "FRw",
            "SAR": "﷼",
            "SBD": "Si$",
            "SCR": "SRe",
            "SDG": ".س.ج",
            "SEK": "kr",
            "SGD": "$",
            "SHP": "£",
            "SLL": "Le",
            "SOS": "Sh.so.",
            "SRD": "$",
            "SSP": "£",
            "STD": "Db",
            "SYP": "LS",
            "SZL": "E",
            "THB": "฿",
            "TJS": "SM",
            "TMT": "T",
            "TND": "ت.د",
            "TOP": "$",
            "TRY": "₺",
            "TTD": "$",
            "TWD": "$",
            "TZS": "TSh",
            "UAH": "₴",
            "UGX": "USh",
            "USD": "$",
            "UYU": "$",
            "UZS": "лв",
            "VES": "Bs",
            "VND": "₫",
            "VUV": "VT",
            "WST": "SAT",
            "XAF": "FCFA",
            "XCD": "$",
            "XOF": "CFA",
            "XPF": "₣",
            "YER": "﷼",
            "ZAR": "R",
            "ZMW": "ZK",
            "ZWL": "$"
        }
    """
    }
    val currencyMap = jsonToHashMap()

    fun getCurrencySymbol(currencyCode: String): String? {
        return currencyMap[currencyCode.uppercase()]
    }
    fun getCurrencyCode(currencySymbol: String): String? {
        return currencyMap.entries.find { it.value == currencySymbol }?.key
    }
}